seed: 0

sampler: lifted_courier
sampler_kwargs:
  domain_filepath: domains/taskographyv5.pddl
  scene_graph_filepath: null
  complexity: 3
  bagslots: 3

dataset: PDDLGymDataset
dataset_kwargs:
  data_dir: /Users/christopheragia/Projects/data/3dscenegraph
  split: tiny
  problem_dir: ./third_party/pddlgym/pddl
  save_samplers: True
  sampler_dir: datasets/samplers/lifted_courier
  train_scenes: 10
  samples_per_train_scene: 4
  samples_per_test_scene: 5
