seed: 0

sampler: courier
sampler_kwargs:
  domain_filepath: domains/taskographyv3.pddl
  scene_graph_filepath: null
  complexity: 3
  bagslots: 3

dataset: PDDLGymDataset
dataset_kwargs:
  data_dir: $DATA/3dscenegraph
  split: tiny
  problem_dir: ./third_party/pddlgym/pddlgym/pddl
  save_samplers: True
  sampler_dir: datasets/samplers/courier
  train_scenes: 10
  samples_per_train_scene: 4
  samples_per_test_scene: 5
