seed: 0

sampler: lifted_rearrangement
sampler_kwargs:
  domain_filepath: domains/taskographyv4.pddl
  scene_graph_filepath: null
  complexity: 1
  bagslots: null

dataset: PDDLGymDataset
dataset_kwargs:
  data_dir: $DATA/3dscenegraph
  split: tiny
  problem_dir: ./third_party/pddlgym/pddlgym/pddl
  save_samplers: True
  sampler_dir: datasets/samplers/lifted_rearrangement
  train_scenes: 10
  samples_per_train_scene: 4
  samples_per_test_scene: 5
